# Generated by Django 5.2.3 on 2025-06-23 19:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event", "0002_location_event_competition"),
        ("offer", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id_booking",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de réservation"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.person",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
            },
        ),
        migrations.CreateModel(
            name="BookingLine",
            fields=[
                (
                    "id_booking_line",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        editable=False,
                        max_length=73,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le QR code doit être de la forme <UUID>|<UUID>.",
                                regex="^[0-9a-fA-F\\-]{36}\\|[0-9a-fA-F\\-]{36}$",
                            )
                        ],
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        editable=False,
                        upload_to="qr_codes",
                        verbose_name="Image du QR Code",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.booking",
                        verbose_name="Réservation",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offer.offer",
                        verbose_name="Offre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de réservation",
                "verbose_name_plural": "Lignes de réservation",
            },
        ),
    ]
