# Generated by Django 5.2 on 2025-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                ("id_sport", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=30, unique=True, verbose_name="Sport"),
                ),
                ("image", models.ImageField(upload_to="sports", verbose_name="Image")),
            ],
            options={
                "verbose_name": "Épreuve sportive",
                "verbose_name_plural": "Épreuves sportives",
            },
        ),
    ]
