# Generated by Django 5.2 on 2025-05-02 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id_location",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Lieu"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Ville")),
                (
                    "total_seats",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(80000)],
                        verbose_name="Nombre total de places",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieu",
                "verbose_name_plural": "Lieux",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id_event", models.SmallAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999.99),
                        ],
                        verbose_name="Prix (€)",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.sport",
                        verbose_name="Épreuve sportive",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.location",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id_competition",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Description"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Femmes", "Femmes"),
                            ("Hommes", "Hommes"),
                            ("Mixte", "Mixte"),
                        ],
                        max_length=6,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Phase"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétition",
                "verbose_name_plural": "Compétitions",
            },
        ),
    ]
